### ISSUE TITLE
how to tweet with a newline

### ISSUE THREAD

**Issue by data-coder** [piroor/tweet.sh#14]
I have a txt file named "a.txt"

cat a.txt
```
line 1
line 2
```
when I do `./tweet.sh post (cat a.txt)` the tweet is:

`line 1 line 2`

Is there anyway to tweet using newlines? 
Thanks!

**Comment by piroor** [comment]
If you run it on Bash, did you try `./tweet.sh post "$(cat a.txt)"` ? Note that the process substitution (`$(...)`) must be wrapped with double quotes.

**Comment by data-coder** [comment]
Thanks for your reply and sorry for the delay. 
On Bash: 
`./tweet.sh post "$(cat a.txt)"`
> {"errors":[{"code":32,"message":"Could not authenticate you."}]}

`./tweet.sh post $(cat a.txt)`
Works, but without newlines.

**Comment by piroor** [comment]
Sorry I've confirmed that the feature was broken... Now "post", "reply" and "direct-message" commands (and their aliases) read posting body from the standard input, so you can do: `cat a.txt | ./tweet.sh post`

**Comment by data-coder** [comment]
Thanks! I will have to update my scripts, though.
