### ISSUE TITLE
Expected behaviour of watch-mentions

### ISSUE THREAD

**Issue by zohar** [piroor/tweet.sh#15]
When I run `./tweet.sh watch -d "echo 'DM'; cat"` I get results which are not related to me. They are related to people I'm connected with but these are replies and tweets which are in no way my DMs .

1. What is the expected behaviour of the command, with or without parameters. 
2. Is the `-k` parameter a mandatory one?

**Comment by piroor** [comment]
Sadly the `watch-mentions` (`watch`) command is no longer available because Twitter doesn't support the streaming API anymore. Instead you need to do polling for each resources: DMs, mentions, and others.
