### ISSUE TITLE
{"errors":[{"code":32,"message":"Could not authenticate you."}]}

### ISSUE THREAD

**Issue by GAZ082** [piroor/tweet.sh#24]
Hi! I'm testing the script out. When doing a simple `./tweet.sh fetch` I get the error of the subject.

This is my `~/.tweet.client.key` file:

```
MY_SCREEN_NAME=Gabrielxxxxx
MY_LANGUAGE=es_AR
CONSUMER_KEY=dwHaZxxxx
CONSUMER_SECRET=rvuXcxxxxx
ACCESS_TOKEN=11268612-ASuxxxxx
ACCESS_TOKEN_SECRET=mmQEU61xxxxx
```

Any tip is welcomed!

Thanks!

**Comment by piroor** [comment]
The "fetch" command requires an ID of a tweet or a URL of a tweet. You looks to forget to specify that.
