### ISSUE TITLE
Did you know kotoriotoko?

### ISSUE THREAD

**Issue by ghost** [piroor/tweet.sh#28]
https://github.com/ShellShoccar-jpn/kotoriotoko

If you thought this issue a spam, you can just ignore this; thought you could learn things from the repository.

**Comment by piroor** [comment]
I know that project. We have different design policies, so it looks hard to import things directly to this project.

By the way, this tweet.sh project was started mainly for demonstrating my shell scripting skills (to promote my book.) Thus this project won't be closed even if features are completely covered by other similar project.
