### ISSUE TITLE
I want only search new Twits of X famous

### ISSUE THREAD

**Issue by edudiy** [piroor/tweet.sh#29]
I'm testing this:

./tweet.sh fetch https://twitter.com/muse
{"errors":[{"code":8,"message":"No data available for specified ID."}]}

How it´s the line_command full for this propuse ?

Thanks and excuse me for my english, I'm spanish

**Comment by piroor** [comment]
The command `fetch` is designed to fetch an individual tweet. You should use `fetch-tweets` instead, like:

```
$ ./tweet.sh fetch-tweets -u muse
```
