### ISSUE TITLE
Deleteing DMs

### ISSUE THREAD

**Issue by cybercottage** [piroor/tweet.sh#32]
Hi More of a feature request , If you are still looking at this , it would be nice to have teh option to delete DMs in the same way as deleting tweets

Ian

Great script by the way.

**Comment by piroor** [comment]
A new command `delete-direct-message` (aka `delete-dm` or `del-dm`) is now available.
https://github.com/piroor/tweet.sh#delete-direct-messages-delete-dm-del-dm-deletes-a-dm
