### ISSUE TITLE
Could not authenticate you for some commands

### ISSUE THREAD

**Issue by rogersm** [piroor/tweet.sh#33]
I just installed it in FreeBSD and I can run 
```
% tweet.sh fetch-favorites
```
succesfully, but I get:
```
% tweet.sh fetch
{"errors":[{"code":32,"message":"Could not authenticate you."}]}
```

Posting tweets also work.

Any ideas where I should look for errors? Is the authentication API different depending on the command?

**Comment by piroor** [comment]
The command `fetch` is designed to fetch an individual tweet. You should use `fetch-tweets` instead. For example, when you fetch tweets of your account:

```
$ ./tweet.sh fetch-tweets -u $(./tweet.sh whoami)
```

**Comment by piroor** [comment]
`tweet.sh` should report error for missing required parameters. I've added some error messages for such cases.
