### ISSUE TITLE
"curl option --form is badly used" when uploading image

### ISSUE THREAD

**Issue by ejstreet** [piroor/tweet.sh#5]
Hi,

I've been playing around with your script and it seems to be the most well documented and comprehensive twitter scripts around. I have been able to successfully send text tweets, however I am struggling to get image uploads to work. My understanding from the example is that I am supposed to first upload the image, then use the media ID in the JSON response in a following tweet. 

Unfortunately, when I run 
`./tweet.sh upload /path/to/image.jpg`

Instead of JSON I get the response: 
`curl: option --form: is badly used here`
`curl: try 'curl --help' or 'curl --manual' for more information`

Am I doing something wrong? Or is it possible that some change to curl has broken the script? All dependencies are the latest version.

**Comment by hacktek** [comment]
Same thing's happening to me, I wonder if my curl version is too old (7.26 seems pretty old tbh).

curl 7.26.0 (arm-unknown-linux-gnueabihf) libcurl/7.26.0 OpenSSL/1.0.1e zlib/1.2.7 libidn/1.25 libssh2/1.4.2 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: Debug GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

 I'm running Raspbian on an RPi2 and this is the latest packaged version. I'll try to build from source and see if that makes a difference.

**Comment by piroor** [comment]
Thank you reporting! I've confirmed this issue with:

 * curl 7.38.0 (Raspbian)
 * curl 7.47.0 (Ubuntu)

**Comment by piroor** [comment]
Fixed by 46bd90622c02bd91e05fe9ddc3a12e578d5ae717 for me. I didn't know the difference of `--data` and `--form`...

**Comment by ejstreet** [comment]
Thanks, I'm now able to get a JSON response, however now when I try to attach an image to a tweet, I get a code 32, "Could not authenticate you." error. This only seems to happen when I try to attach media. I tried using both `media_id` and `media_id_string` values, but neither seem to work.

**Comment by moisesalvarez** [comment]
I had the same error code 32, "Could not authenticate you." trying to use media_id, it was not related to authentication but to the format of the request send to Twitter (it should return a `400 BAD REQUEST ` instead). 
I have solved it editing `post()` function line 1000. The equals sign associated to media_params must be removed so it ends like this:
`        media_params="media_ids $OPTARG"` 
So later in `call_api()` its correctly assigned an equals sign instead of escaping it into  %3D in `to_encoded_list` function  (which breaks request)

**Comment by adeluccar** [comment]
Version: https://github.com/piroor/tweet.sh/commit/5bbfce9fa663bb602dbb522f00cdcad291a746ea

Running `./tweet.sh upload /path/to/image.jpg`

Throws the following error:

```curl: option --form: is badly used here```
```curl: try 'curl --help' or 'curl --manual' for more information```

@moisesalvarez's solution at https://github.com/piroor/tweet.sh/issues/5#issuecomment-313846196 no longer references the proper line to change.

Is there a fix planned for this issue?

Thank you, @piroor

**Comment by piroor** [comment]
I've confirmed that curl 7.58.0 on Ubuntu (18.04LTS) works as expected with no error.

```
$ curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
$ ./tweet.sh upload /path/to/photo.png
{"media_id":...,"media_id_string":"...","size":2130,"expires_after_secs":86400,"image":{"image_type":"image\/png","w":32,"h":32}}
```

If you see any error around curl, please check its version and include it to your comment. Thanks.

**Comment by istemihan90** [comment]
just use "" for any path
